<a href="https://colab.research.google.com/github/Satnam-12/Linear-Algebra-58019/blob/main/Finals_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Number 1: 
Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? 

In [21]:
A = np.array([[1,1,1],[1,0,4],[0,0,5]])#the creation of matrix
B = np.array([[89],[89],[95]])#creaton of matrix
amt = np.linalg.inv(A).dot(B)#to solve for the answer
print(amt)#to get the answer

[[13.]
 [57.]
 [19.]]


#Number 2:
 3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [19]:
import numpy as np
from scipy.linalg import solve
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #creation of matrix
print(A)#to print the matrix
print()
B = np.array([[5],[15],[-20]])#creation of matrix
print(B)#to print the matrix
print()
X = np.linalg.solve(A,B)#to solve for the equation
print(X)#to print the result.
print()
#since its a singluar matrix it will not work, Since the determinant is 0, we can’t find the inverses of such matrices.

[[  3  -1   0]
 [  9  -3   3]
 [-12   4  -4]]

[[  5]
 [ 15]
 [-20]]



LinAlgError: ignored

#Number 3:
Find the eigenvalue/s

Find the eigenvectors


In [ ]:
import numpy as np 
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) # creation of matrix
print(A) 
print()
w,v = np.linalg.eig(A)#to show the eigenvalue and elegenfavtors.
print("The eigenvalue/s is/are:/n",w)#to show eigenvalues 
print()
print("The right eigenvectors are:/n",v.round())#to show eigenvectors and used v.round to round off


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The eigenvalue/s is/are:/n [-1.  3.  2.]

The right eigenvectors are:/n [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
