<a href="https://colab.research.google.com/github/Satnam-12/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)


In [ ]:
import numpy as np #import Library
A = np.array([[4,3,2,1,0],[-2,2,3,7,8],[3,-5,2,7,9],[3,-5,2,3,2],[3,-5,2,1,2]])#5X5 matrix
print("Square Matrix")
print()
print(A)

Square Matrix

[[ 4  3  2  1  0]
 [-2  2  3  7  8]
 [ 3 -5  2  7  9]
 [ 3 -5  2  3  2]
 [ 3 -5  2  1  2]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)



In [17]:
import numpy as np #import Library
A= np.array([[1,2,3],[0,4,5],[0,0,6]])#square matrix whose elements below the principal diagonal are zero 
print(A)

[[1 2 3]
 [0 4 5]
 [0 0 6]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [24]:
import numpy as np #import Library
A = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
B = np.transpose(A)#to make it symmetrical
print(A)
print()
print(B)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [22]:
import numpy as np #import Library
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

invC = np.linalg.inv(C)# to get the inverse of the matrix
print(C)
print()
print("Inverse of Matrix C:")
print(invC)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Inverse of Matrix C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [18]:
import numpy as np #import Library
A = np.array ([[1,2,3],
               [4,5,6],
               [7,8,-9]])

detOfA = np.linalg.det(A)#detirminant
print(A)
print()
print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 -9]]

Determinant of the given matrix in Question 4:
53


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [ ]:
import numpy as np #import Library
A = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])

B = np.array([[[3.4],
               [8.8],
               [19.2]]])

roots = np.linalg.inv(A) @ B#finding of roots
print(A)
print()
print("Roots of the given linear equations:")
print(roots)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

Roots of the given linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
