<a href="https://colab.research.google.com/github/Satnam-12/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1. Consider the four matrices

In [23]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print("A=")
print(A)
print()
import numpy as np
B = np.array([[1,2],[3,4],[5,6]])
print("B=")
print(B)
print()
import numpy as np
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("C=")
print(C)
print()
import numpy as np
D = np.array([[1,2],[3,4]])
print("D=")
print(D)
print()
dot = np.dot(A,B)
print("a=AB")
print(dot)
print()
print("b=D+D")
print(D+D)
print()
print("c=2*C")
print(2*C)
print()

A=
[[1 2 3]
 [4 5 6]]

B=
[[1 2]
 [3 4]
 [5 6]]

C=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

D=
[[1 2]
 [3 4]]

a=AB
[[22 28]
 [49 64]]

b=D+D
[[2 4]
 [6 8]]

c=2*C
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]



## Given the linear combination below, try to create a corresponding matrix representing it and display its type, shape, and its dimension.

In [43]:
import numpy as np
A = np.array([5,3,-1])


print('Size of array')
print(A.size)
print()
print('Type of array')
print(type(A))
print()
print('Shape of array')
print(A.shape)
print()
print('Dimesnion of array')
print(A.ndim)
print()



Size of array
3

Type of array
<class 'numpy.ndarray'>

Shape of array
(3,)

Dimesnion of array
1

