<a href="https://colab.research.google.com/github/Satnam-12/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim exam



##Question 1
###Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [7]:
import numpy as np
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##Question 2
###In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [10]:
import numpy as np
C = np.eye(4)
print(2*C)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


##Question 3
###Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [12]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
C = np.cross(A,B)
print(C)

[20 -4 -3]
